# Generated by Django 5.2 on 2025-05-07 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agenttask_error_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='agenttaskstep',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_agent_user_name'),
        ),
        migrations.AddConstraint(
            model_name='agenttaskstep',
            constraint=models.UniqueConstraint(fields=('task', 'step_number'), name='unique_agent_task_step_task_step_number'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_api_key_user_name'),
        ),
    ]
